version: '3.7'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./public:/var/www/html
